export { default as Header } from "./header/header";
export { default as Navigation } from "./navigation/navigation";
export { default as Hero } from "./home-page/hero/hero";
export { default as StatsSection } from "./home-page/stats/stats";
export { default as Age } from "./home-page/age/age";
export { default as Partners } from "./home-page/partners/partners";
export { default as Advantages } from "./home-page/advantages/advantages";
export { default as Footer } from "./footer/footer";
export { default as EquipmentTable } from "./equipment-table/equipment-table";
export { default as AboutHeroSection } from "./about-page/hero/hero";
export { default as AboutMissionSection } from "./about-page/mission/mission";
export { default as AboutValuesSection } from "./about-page/values/values";
export { default as AboutHistorySection } from "./about-page/history/history";
export { default as AboutTeamSection } from "./about-page/team/team";
export { default as AboutContactSection } from "./about-page/contact/contact";
export { default as AboutMapSection } from "./about-page/map/map";
export { default as CareerHeroSection } from "./career-page/hero/hero";
export { default as CareerFiltersSection } from "./career-page/filters/filters";
export { default as CareerVacanciesList } from "./career-page/vacancies/vacancies";
export { default as CareerHiringProcess } from "./career-page/hiring-process/hiring-process";
export { default as CareerContactsSection } from "./career-page/contacts/contacts";
export {default as ResourcesHeroSection} from "./resources-page/hero/hero";
export {default as ResourcesStatsSection} from "./resources-page/stats/stats";
export {default as ResourcesGrid} from "./resources-page/resources-grid/resources-grid";
export {default as ResourcesMapSection} from "./resources-page/map/map";
export {default as ResourcesManagementSystemSection} from "./resources-page/management/management";
